version: '3'
services:
  mongodb:
    image: "docker.io/library/mongo:latest"
    container_name: "mongodb"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - '27017:27017'
